server:
  port: 9090
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024
spring:
  datasource:
    url: jdbc:avatica:remote:url=http://10.89.57.187:8888/druid/v2/sql/avatica/;transparent_reconnection=true
    driver-class-name: org.apache.calcite.avatica.remote.Driver

